import Head from "next/head";
import Image from "next/image";
import Meta from "@components/Meta";
import { PostCard, Categories } from "../components";

const posts = [
  { title: "In the night", excerpt: "i is exclide" },
  { title: "I hear them talk", excerpt: "i is exclide" },
  { title: "Coldest story", excerpt: "i is exclide" },
];

export default function Home() {
  return (
    <div className="container mx-auto p-10">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Meta
        pageMeta={{
          title: "Protean Industries",
          description: "Welcome to the Protean Blog",
        }}
      />

      <main>
        <PostCard />
        <Categories />
        <h1 className="text-4xl">Home is a place in heaven</h1>
        {posts.map((post) => (
          <article>
            {post.title}
            {post.excerpt}
          </article>
        ))}
      </main>
    </div>
  );
}
